name: build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: trim21/actions/setup-go@master

      - run: sudo apt update
      - run: sudo apt install libgpgme-dev libassuan-dev libbtrfs-dev libdevmapper-dev pkg-config -y

      - run: go build -o dist/imagesync ./cmd/imagesync/
      - run: dist/imagesync --help
