name: build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version-file: 'go.mod'

      - uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: libgpgme-dev libassuan-dev libbtrfs-dev libdevmapper-dev pkg-config
          version: '1'

      - run: go build ./cmd/imagesync/
