name: Security Vulnerability Check

on:
  push:
    branches-ignore:
      - renovate/**
    paths:
      - "**.go"
      - "go.mod"
      - "go.sum"
      - ".golangci.yaml"
      - ".github/workflows/security.yaml"
  pull_request:
    branches:
      - master
    paths:
      - "**.go"
      - "go.mod"
      - "go.sum"
      - ".github/workflows/security.yaml"
  schedule:
    - cron: "45 8 * * 5"

jobs:
  vulnerability-scan:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - uses: trim21/actions/setup-go@master

      - run: sudo apt update
      - run: sudo apt install libgpgme-dev libassuan-dev libbtrfs-dev libdevmapper-dev pkg-config -y

      - run: go run golang.org/x/vuln/cmd/govulncheck ./...

      - name: Notify failed build
        uses: jayqi/failed-build-issue-action@1a893bbf43ef1c2a8705e2b115cd4f0fe3c5649b # v1
        if: failure()
        with:
          github-token: ${{ github.token }}
          label-name: vulncheck
